FIELD_MAPPINGS = {
            # Provider fields
            "provider_name": [
                "provider_name",
                "Provider Name",
                "Hospital Name",
                "hospital_name",
                "facility_name",
                "Facility Name",
            ],
            "provider_address": [
                "provider_address",
                "Provider Address",
                "Address",
                "Street Address",
                "provider_location",
                "Provider Location",
                "Location",
                "facility_address",
            ],
            "provider_city": [
                "provider_city",
                "Provider City",
                "City",
                "facility_city",
            ],
            "provider_state": [
                "provider_state",
                "Provider State",
                "State",
                "facility_state",
            ],
            "provider_zip": [
                "provider_zip",
                "Provider ZIP",
                "ZIP",
                "Zip Code",
                "postal_code",
                "facility_zip",
            ],
            "provider_country": [
                "provider_country",
                "Provider Country",
                "Country",
                "facility_country",
            ],
            "provider_phone": [
                "provider_phone",
                "Provider Phone",
                "Phone",
                "Phone Number",
                "contact_number",
                "facility_phone",
            ],
            "provider_lat": [
                "provider_lat",
                "Provider Latitude",
                "Latitude",
                "lat",
                "facility_lat",
            ],
            "provider_lng": [
                "provider_lng",
                "Provider Longitude",
                "Longitude",
                "lng",
                "lon",
                "facility_lng",
            ],
            "provider_specialty": [
                "provider_specialty",
                "Provider Specialities",
                "Provider Specialty",
                "Specialty",
                "Specialties",
                "facility_specialty",
            ],
            "provider_benefits": [
                "provider_benefits",
                "Provider Benefits",
                "Benefits",
                "Additional Services",
                "facility_benefits",
            ],
            # Service fields
            "service_name": [
                "service_name",
                "Service Name",
                "Service",
                "Procedure Name",
                "procedure_name",
            ],
            "service_code": [
                "service_code",
                "Service Code",
                "Code",
                "Procedure Code",
                "CPT Code",
                "cpt_code",
                "procedure_code",
            ],
            "service_category": [
                "service_category",
                "Service Category",
                "Category",
                "Department",
                "procedure_category",
            ],
            "setting": [
                "setting",
                "Setting",
                "Care Setting",
                "Service Setting",
                "location_setting",
            ],
            "service_description": [
                "service_description",
                "Service Description",
                "Description",
                "Procedure Description",
                "procedure_description",
            ],
            # Insurance fields
            "insurance_name": [
                "insurance_name",
                "Insurance Name",
                "Payer Name",
                "Insurance Company",
                "payer",
            ],
            "plan_name": [
                "plan_name",
                "Plan Name",
                "Insurance Plan",
                "insurance_type",
                "Plan Type",
            ],
            "insurance_benefits": [
                "insurance_benefits",
                "Insurance Benefits",
                "Benefits",
                "Coverage Details",
                "plan_benefits",
            ],
            # Pricing fields
            "standard_charge": [
                "standard_charge",
                "Standard Charge",
                "Standard Price",
                "List Price",
            ],
            "negotiated_price": [
                "negotiated_price",
                "Negotiated Price",
                "Contracted Price",
            ],
            "in_network": [
                "in_network",
                "In Network",
                "InNetwork",
                "Network Status",
            ],
        }



HEADERS = {
    "provider_name": "Provider Name",
    "provider_address": "Address",
    "provider_city": "City",
    "provider_state": "State",
    "provider_zip": "Zip Code",
    "provider_phone": "Phone Number",
    "provider_country": "Country",
    "provider_lat": "Latitude",
    "provider_lng": "Longitude",
    "provider_specialty": "Provider Specialities",
    "provider_benefits": "Provider Benefits",
    "service_category": "Service Category",
    "service_name": "Service Name",
    "service_code": "Service Code",
    "service_description": "Service Description",
    "setting": "Setting",
    "standard_charge": "Standard Charge",
    "insurance_name": "Insurance Name",
    "plan_name": "Plan Name",
    "negotiated_price": "Negotiated Price",
    "in_network": "In Network",
    "insurance_benefits": "Insurance Benefits",
}
